- label: bin
  model_filepath: "package://binpicking_simple_utils/collision_objects/meshes/bin.stl"
  x_position: 0.5
  y_position: 0.0
  z_position: 0.5
  roll: 1.570
  pitch: 0
  yaw: 0
  x_scale: 1
  y_scale: 1
  z_scale: 1

- label: ceiling
  model_filepath: "package://binpicking_simple_utils/collision_objects/meshes/box.stl"
  x_position: 0
  y_position: 0
  z_position: 2
  roll: 0
  pitch: 0
  yaw: 0
  x_scale: 25
  y_scale: 25
  z_scale: 0.5

- label: left_wall
  model_filepath: "package://binpicking_simple_utils/collision_objects/meshes/box.stl"
  x_position: 0
  y_position: 1.275
  z_position: 0.725
  roll: 0
  pitch: 0
  yaw: 0
  x_scale: 25
  y_scale: 0.5
  z_scale: 25

- label: right_wall
  model_filepath: "package://binpicking_simple_utils/collision_objects/meshes/box.stl"
  x_position: 0
  y_position: -1.275
  z_position: 0.725
  roll: 0
  pitch: 0
  yaw: 0
  x_scale: 25
  y_scale: 0.5
  z_scale: 25

- label: back_wall
  model_filepath: "package://binpicking_simple_utils/collision_objects/meshes/box.stl"
  x_position: -1.275
  y_position: 0
  z_position: 0.725
  roll: 0
  pitch: 0
  yaw: 0
  x_scale: 0.5
  y_scale: 25
  z_scale: 25
