#bin_center_x: 1.28
bin_center_x: 0.4
bin_center_y: 0.0
bin_center_z: 0.2

bin_size_x: 0.35
bin_size_y: 0.2
bin_size_z: 0.15

roll_default: 0
pitch_default: 3.14
yaw_default: 0

roll_range: 0.7
pitch_range: 0.7
yaw_range: 6.2

approach_distance: 0.10
deapproach_height: 0.0

#Parametre iba pre stomp test
step_x: 0.03
step_y: 0.03
step_z: 0.03

step_roll: 0.3
step_pitch: 0.3
step_yaw: 0.6

virtual_robot:
  start_pose: [0.0, 0.0, 1.7, 0.0, 1.51, 0.00 ]
  end_pose: [0.0, 0.0, 1.7, 0.0, 1.51, 0.00 ]