#bin_center_x: 1.28
bin_center_x: -1.2
bin_center_y: 1.6
bin_center_z: 1.0

bin_size_x: 0.3
bin_size_y: 0.3
bin_size_z: 0.3

roll_default: 0
pitch_default: 3.14
yaw_default: 0

roll_range: 0.7
pitch_range: 0.7
yaw_range: 6.2

approach_distance: 0.10
deapproach_height: 0.0

#Parametre iba pre stomp test
step_x: 0.03
step_y: 0.03
step_z: 0.03

step_roll: 0.3
step_pitch: 0.3
step_yaw: 0.6

virtual_robot:
  start_pose: [1.99, -0.22, 0.204, 0.014, 1.51, 0.78 ]
  end_pose: [1.99, -0.22, 0.204, 0.014, 1.51, 0.78 ]