#bin_center_x: 1.28
bin_center_x: 0.42
bin_center_y: 0.0
bin_center_z: 0.1

bin_size_x: 0.21
bin_size_y: 0.5
bin_size_z: 0.3

roll_default: 0
pitch_default: 3.14
yaw_default: 0

roll_range: 0.707
pitch_range: 0.707
yaw_range: 1.54

approach_distance: 0.10
deapproach_height: 0.0

#Parametre iba pre stomp test
step_x: 0.1
step_y: 0.1
step_z: 0.1

step_roll: 0.3
step_pitch: 0.3
step_yaw: 0.3
