# BIN VOLUME TYPE
# 0 Cube
# 1 Cube Random
# 2 Point Cloud
# 3 Point Cloud Random
# 4 Single Pose
bin_volume_type: 2

x_rotation: 0.0
y_rotation: 0.0
z_rotation: 0.0

roll_default: 0.0
pitch_default: 3.14
yaw_default: 0

roll_range: 0.7
pitch_range: 0.7
yaw_range: 6.28

step_roll: 0.3
step_pitch: 0.3
step_yaw: 1.2

mesh: "/home/controller/catkin_ws/src/pcl_binvox/data/object_1_shifted.ply"

