# BIN VOLUME TYPE
# 0 Cube
# 1 Cube Random
# 2 Point Cloud
# 3 Point Cloud Random
# 4 Single Pose
bin_volume_type: 4

position:
  x: 0.5
  y: 0.0
  z: 0.5
orientation:
  x: 0.0
  y: 0.0
  z: 0.0
  w: 1.0