# BIN VOLUME TYPE
# 0 Cube
# 1 Cube Random
# 2 Point Cloud
# 3 Point Cloud Random
# 4 Single Pose
bin_volume_type: 2

x_rotation: 0.0
y_rotation: 0.0
z_rotation: 0.0

roll_min: -0.05
roll_max: 0.05
pitch_min: -0.05
pitch_max: 0.05
yaw_min: -0.05
yaw_max: 0.05

step_roll: 0.1
step_pitch: 0.1
step_yaw: 0.1

mesh: "/home/controller/catkin_ws/src/pcl_binvox/data/object_1_shifted.ply"

