# BIN VOLUME TYPE
# 0 Cube
# 1 Cube Random
# 2 Point Cloud
# 3 Point Cloud Random
# 4 Single Pose
bin_volume_type: 4

position:
  x: 1.4
  y: -0.26
  z: -0.36
orientation:
  x: 0.586
  y: -0.792
  z: 0.103
  w: -0.140
