#bin_center_x: 1.28
bin_center_x: 1.25
bin_center_y: 0.0
bin_center_z: 1.6

bin_size_x: 0.2
bin_size_y: 0.5
bin_size_z: 0.05

roll_default: 0.0
pitch_default: 3.14
yaw_default: 0.0

roll_range: 1.5
pitch_range: 1.5
yaw_range: 6.2

approach_distance: 0.10
deapproach_height: 0.0

#Parametre iba pre stomp test
step_x: 0.05
step_y: 0.05
step_z: 0.05

step_roll: 0.3
step_pitch: 0.3
step_yaw: 0.6

virtual_robot:
  start_pose: [0.0, 0.0, 0.0, 0.0, -1.42, 0.0 ]
  end_pose: [0.0, 0.0, 0.0, 0.0, -1.42, 0.0 ]
